name: Deploy Portfolio to Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Build Next.js Frontend
        run: |
          cd client
          npm ci
          npm run build
          tar -czf next-build.tar.gz .next

      - name: Install Ansible
        run: pip install ansible

      - name: Generate Ansible Secrets File
        run: |
          mkdir -p configuration/vars
          cat << EOF >> configuration/vars/secrets.yml
          env_secret_key: "${{ secrets.DJANGO_SECRET_KEY }}"
          env_debug: "${{ secrets.DJANGO_DEBUG }}"
          env_allowed_hosts: "${{ secrets.DJANGO_ALLOWED_HOSTS }}"
          env_email_host_user: "${{ secrets.EMAIL_HOST_USER }}"
          env_email_host_password: "${{ secrets.EMAIL_HOST_PASSWORD }}"
          EOF

      - name: Set up SSH Access to Azure VM
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AZURE_VM_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.AZURE_VM_IP }} >> ~/.ssh/known_hosts

      - name: Execute Ansible Deploy Playbook
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
        run: |
          cd configuration
          ansible-playbook -i "${{ secrets.AZURE_VM_IP }}," -u azureuser --private-key ~/.ssh/id_rsa deploy.yml